package infra

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ElioNeto/vyx/core/domain/infra"
)

// StackLoader loads infrastructure definitions from various sources.
type StackLoader struct {
	projectDir string
}

// NewStackLoader creates a StackLoader rooted at the given directory.
func NewStackLoader(projectDir string) *StackLoader {
	return &StackLoader{projectDir: projectDir}
}

// LoadFromInfraMap reads infra_map.json (generated by the scanner).
func (l *StackLoader) LoadFromInfraMap(stackName string) (*infra.Stack, error) {
	path := filepath.Join(l.projectDir, "infra_map.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("load infra_map.json: %w", err)
	}

	var resourceMap struct {
		Resources []infraResourceJSON `json:"resources"`
		Stacks    []struct {
			Name      string              `json:"name"`
			Resources []infraResourceJSON `json:"resources"`
		} `json:"stacks,omitempty"`
	}

	if err := json.Unmarshal(data, &resourceMap); err != nil {
		return nil, fmt.Errorf("parse infra_map.json: %w", err)
	}

	// Determine which resources to use.
	var resources []infraResourceJSON
	if stackName != "" && stackName != "default" {
		// Look for a named stack.
		for _, s := range resourceMap.Stacks {
			if s.Name == stackName {
				resources = s.Resources
				break
			}
		}
	}
	if len(resources) == 0 {
		resources = resourceMap.Resources
	}

	stack := infra.NewStack(stackName)
	for _, r := range resources {
		res := &infra.Resource{
			ID:           infra.ResourceID(r.ID),
			Type:         infra.ResourceType(r.Type),
			ProviderName: infra.ProviderID(r.Provider),
			Properties:   r.Properties,
			DependsOn:    convertIDs(r.DependsOn),
			Tags:         r.Tags,
			Outputs:      convertOutputs(r.Outputs),
			State:        infra.ResourceStatePending,
		}
		stack.AddResource(res)
	}

	return stack, nil
}

// LoadFromVyxYaml reads the infrastructure section from vyx.yaml.
func (l *StackLoader) LoadFromVyxYaml(stackName string) (*infra.Stack, error) {
	path := filepath.Join(l.projectDir, "vyx.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("load vyx.yaml: %w", err)
	}

	// Simple YAML parsing for the infrastructure section.
	// We look for "infrastructure:" and parse the resources list.
	content := string(data)
	stack := infra.NewStack(stackName)

	// Find infrastructure section and parse resource definitions inline.
	// For now, support a minimal YAML subset for resources.
	// In production, use a proper YAML parser (already available via gopkg.in/yaml.v3).

	// Check if there's an infra_map.json alongside
	infraMapPath := filepath.Join(l.projectDir, "infra_map.json")
	if _, err := os.Stat(infraMapPath); err == nil {
		return l.LoadFromInfraMap(stackName)
	}

	// Parse inline resources from YAML (minimal parser for the resources list)
	resources := parseInlineResources(content)
	for _, r := range resources {
		stack.AddResource(r)
	}

	return stack, nil
}

// LoadStack is the unified entry point: tries infra_map.json first, then vyx.yaml.
func (l *StackLoader) LoadStack(stackName string) (*infra.Stack, error) {
	// Try infra_map.json first (scanner output)
	stack, err := l.LoadFromInfraMap(stackName)
	if err == nil && stack.ResourceCount() > 0 {
		return stack, nil
	}

	// Fall back to vyx.yaml inline definitions
	stack, err = l.LoadFromVyxYaml(stackName)
	if err == nil && stack.ResourceCount() > 0 {
		return stack, nil
	}

	// If neither has resources, create an empty stack
	return infra.NewStack(stackName), nil
}

// infraResourceJSON matches the JSON format in infra_map.json.
type infraResourceJSON struct {
	Type      string            `json:"type"`
	Provider  string            `json:"provider"`
	ID        string            `json:"id"`
	Properties map[string]any   `json:"properties"`
	DependsOn []string          `json:"depends_on,omitempty"`
	Tags      map[string]string `json:"tags,omitempty"`
	Outputs   []string          `json:"outputs,omitempty"`
}

func convertIDs(ids []string) []infra.ResourceID {
	if ids == nil {
		return nil
	}
	result := make([]infra.ResourceID, len(ids))
	for i, id := range ids {
		result[i] = infra.ResourceID(id)
	}
	return result
}

func convertOutputs(outputs []string) map[string]string {
	if outputs == nil {
		return nil
	}
	result := make(map[string]string, len(outputs))
	for _, name := range outputs {
		result[name] = "" // Output values populated by provider after apply
	}
	return result
}

// parseInlineResources does a minimal parse of vyx.yaml for infrastructure resources.
// This is a simplified parser — production code would use gopkg.in/yaml.v3.
func parseInlineResources(content string) []*infra.Resource {
	var resources []*infra.Resource

	lines := strings.Split(content, "\n")
	inInfra := false
	inResources := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if trimmed == "infrastructure:" || strings.HasPrefix(trimmed, "infrastructure:") {
			inInfra = true
			continue
		}
		if inInfra && (strings.HasPrefix(trimmed, "resources:") || strings.HasPrefix(trimmed, "resources:")) {
			inResources = true
			continue
		}

		// Exit infrastructure section if we hit a top-level key
		if inInfra && !inResources && len(line) > 0 && line[0] != ' ' && line[0] != '\t' {
			inInfra = false
		}

		if inResources && strings.HasPrefix(trimmed, "- type:") {
			typeVal := strings.TrimSpace(strings.TrimPrefix(trimmed, "- type:"))
			typeVal = strings.Trim(typeVal, "\"'")
			r := &infra.Resource{
				Type:       infra.ResourceType(typeVal),
				Properties: make(map[string]any),
				Tags:       make(map[string]string),
				State:      infra.ResourceStatePending,
			}
			resources = append(resources, r)
		} else if inResources && strings.HasPrefix(trimmed, "id:") && len(resources) > 0 {
			val := strings.TrimSpace(strings.TrimPrefix(trimmed, "id:"))
			val = strings.Trim(val, "\"'")
			resources[len(resources)-1].ID = infra.ResourceID(val)
		} else if inResources && strings.HasPrefix(trimmed, "provider:") && len(resources) > 0 {
			val := strings.TrimSpace(strings.TrimPrefix(trimmed, "provider:"))
			val = strings.Trim(val, "\"'")
			resources[len(resources)-1].ProviderName = infra.ProviderID(val)
		}
	}

	return resources
}
