// Package templater implements export of vyx infrastructure definitions
// to other IaC formats: Terraform HCL, CloudFormation, etc.
package templater

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"

	"github.com/ElioNeto/vyx/core/domain/infra"
)

// Format represents an output IaC format.
type Format string

const (
	FormatTerraform     Format = "terraform"
	FormatCloudFormation Format = "cloudformation"
)

// Mapping maps a vyx resource type to its Terraform type name.
var awsTerraformTypes = map[infra.ResourceType]string{
	"aws_s3_bucket":             "aws_s3_bucket",
	"aws_instance":              "aws_instance",
	"aws_db_instance":           "aws_db_instance",
	"aws_iam_role":              "aws_iam_role",
	"aws_lambda_function":       "aws_lambda_function",
	"aws_vpc":                   "aws_vpc",
	"aws_sqs_queue":             "aws_sqs_queue",
	"aws_sns_topic":             "aws_sns_topic",
	"aws_route53_zone":          "aws_route53_zone",
	"aws_elasticache_cluster":   "aws_elasticize_cluster",
	"aws_api_gateway_rest_api":  "aws_api_gateway_rest_api",
}

// Mapping maps a vyx resource type to its CloudFormation type name.
var awsCloudFormationTypes = map[infra.ResourceType]string{
	"aws_s3_bucket":             "AWS::S3::Bucket",
	"aws_instance":              "AWS::EC2::Instance",
	"aws_db_instance":           "AWS::RDS::DBInstance",
	"aws_iam_role":              "AWS::IAM::Role",
	"aws_lambda_function":       "AWS::Lambda::Function",
	"aws_vpc":                   "AWS::EC2::VPC",
	"aws_sqs_queue":             "AWS::SQS::Queue",
	"aws_sns_topic":             "AWS::SNS::Topic",
	"aws_route53_zone":          "AWS::Route53::HostedZone",
	"aws_elasticache_cluster":   "AWS::ElastiCache::CacheCluster",
	"aws_api_gateway_rest_api":  "AWS::ApiGateway::RestApi",
}

// ─── Terraform HCL Export ──────────────────────────────────────────────

const terraformTmpl = `# Generated by vyx — do not edit manually
# Provider: {{ .Provider }}
# Stack:   {{ .StackName }}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "{{ .Region }}"
}

{{ range .Resources }}
{{ .TerraformBlock }}
{{ end }}

{{ range .Outputs }}
output "{{ .Name }}" {
  value = {{ .Value }}
}
{{ end }}
`

// TerraformResource represents a single Terraform resource.
type TerraformResource struct {
	ID       string
	Type     string
	Properties string
	DependsOn string
}

// TerraformBlock returns the HCL block for a resource.
func (r *TerraformResource) TerraformBlock() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("resource %q %q {\n", r.Type, r.ID))
	b.WriteString(r.Properties)
	if r.DependsOn != "" {
		b.WriteString(fmt.Sprintf("  depends_on = %s\n", r.DependsOn))
	}
	b.WriteString("}\n")
	return b.String()
}

// TerraformOutput represents a Terraform output block.
type TerraformOutput struct {
	Name  string
	Value string
}

// ExportTerraform generates a Terraform HCL file from a stack.
func ExportTerraform(stack *infra.Stack, region string) (string, error) {
	if region == "" {
		region = "us-east-1"
	}

	var resources []TerraformResource
	var outputs []TerraformOutput
	var allErrs []string

	for _, r := range stack.Resources {
		tfType, ok := awsTerraformTypes[r.Type]
		if !ok {
			allErrs = append(allErrs, fmt.Sprintf("resource %q: no Terraform mapping for type %q", r.ID, r.Type))
			continue
		}

		var props strings.Builder
		for k, v := range r.Properties {
			props.WriteString(fmt.Sprintf("  %s = %q\n", k, fmt.Sprintf("%v", v)))
		}

		var deps []string
		for _, dep := range r.DependsOn {
			deps = append(deps, fmt.Sprintf("%q", dep))
		}
		depStr := ""
		if len(deps) > 0 {
			depStr = "[" + strings.Join(deps, ", ") + "]"
		}

		resources = append(resources, TerraformResource{
			ID:         string(r.ID),
			Type:       tfType,
			Properties: props.String(),
			DependsOn:  depStr,
		})

		for name := range r.Outputs {
			outputs = append(outputs, TerraformOutput{
				Name:  fmt.Sprintf("%s_%s", r.ID, name),
				Value: fmt.Sprintf("%s.%s", tfType, name),
			})
		}
	}

	if len(allErrs) > 0 {
		return "", fmt.Errorf("export errors: %s", strings.Join(allErrs, "; "))
	}

	data := map[string]any{
		"Provider":  "aws",
		"Region":    region,
		"StackName": stack.Name,
		"Resources": resources,
		"Outputs":   outputs,
	}

	tmpl, err := template.New("terraform").Parse(terraformTmpl)
	if err != nil {
		return "", fmt.Errorf("parse terraform template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute terraform template: %w", err)
	}

	return buf.String(), nil
}

// ─── CloudFormation Export ──────────────────────────────────────────────

// ExportCloudFormation generates a CloudFormation template from a stack.
func ExportCloudFormation(stack *infra.Stack) (string, error) {
	var b strings.Builder
	b.WriteString("{\n  \"AWSTemplateFormatVersion\": \"2010-09-09\",\n")
	b.WriteString(fmt.Sprintf("  \"Description\": \"vyx infrastructure: %s\",\n", stack.Name))
	b.WriteString("  \"Resources\": {\n")

	var allErrs []string
	var resourceEntries []string

	for i, r := range stack.Resources {
		cfType, ok := awsCloudFormationTypes[r.Type]
		if !ok {
			allErrs = append(allErrs, fmt.Sprintf("resource %q: no CloudFormation mapping for type %q", r.ID, r.Type))
			continue
		}

		entries := make([]string, 0)
		for k, v := range r.Properties {
			entries = append(entries, fmt.Sprintf("      \"%s\": %q", k, fmt.Sprint(v)))
		}

		dependsOn := ""
		if len(r.DependsOn) > 0 {
			depList := make([]string, 0)
			for _, dep := range r.DependsOn {
				depList = append(depList, fmt.Sprintf("%q", dep))
			}
			dependsOn = fmt.Sprintf(",\n      \"DependsOn\": [%s]", strings.Join(depList, ", "))
		}

		comma := ","
		if i == len(stack.Resources)-1 {
			comma = ""
		}

		entry := fmt.Sprintf("    %q: {\n      \"Type\": %q,\n      \"Properties\": {\n%s\n      }%s\n    }%s",
			r.ID, cfType, strings.Join(entries, ",\n"), dependsOn, comma)
		resourceEntries = append(resourceEntries, entry)
	}

	if len(allErrs) > 0 {
		return "", fmt.Errorf("export errors: %s", strings.Join(allErrs, "; "))
	}

	b.WriteString(strings.Join(resourceEntries, "\n"))
	b.WriteString("\n  },\n")

	// Outputs section
	outputEntries := make([]string, 0)
	for _, r := range stack.Resources {
		for name := range r.Outputs {
			_ = name
			outputEntries = append(outputEntries,
				fmt.Sprintf("    %s%s: {\n      \"Value\": { \"Fn::GetAtt\": [\"%s\", \"Arn\"] }\n    }",
					r.ID, name, r.ID))
		}
	}

	if len(outputEntries) > 0 {
		b.WriteString("  \"Outputs\": {\n")
		for i, entry := range outputEntries {
			comma := ","
			if i == len(outputEntries)-1 {
				comma = ""
			}
			b.WriteString(entry + comma + "\n")
		}
		b.WriteString("  },\n")
	}

	b.WriteString("  \"Parameters\": {}\n")
	b.WriteString("}\n")

	return b.String(), nil
}

// ─── Utility ────────────────────────────────────────────────────────────

// FormatList returns a sorted, newline-separated list for display.
func FormatList(resources []*infra.Resource) string {
	var lines []string
	for _, r := range resources {
		lines = append(lines, fmt.Sprintf("  %s [%s]", r.ID, r.Type))
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n")
}
