version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - staticcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - text: "Error return value of .* is not checked"
        linters:
          - errcheck
      - text: "const _[a-zA-Z]+ is unused"
        linters:
          - unused
      - text: "QF1003"
        linters:
          - staticcheck